[build]
  publish = "public"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "public"

# Function configuration
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]

# Direct API access - this allows direct access to the API function without the /api prefix
[[redirects]]
  from = "/tasks*"
  to = "/.netlify/functions/api/tasks:splat"
  status = 200
  force = true

# Traditional API access - this routes /api/* requests to our serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For better cold start performance
[build.environment]
  NODE_VERSION = "18"
