[build]
  publish = "public"
  command = "npm run build"
  functions = "netlify/functions"
  
  # Ensure we're using Node.js 18.x for functions
  environment = { NODE_VERSION = "18" }

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "public"

# Function configuration
[functions]
  # Use the default bundler for simplicity
  node_bundler = "esbuild"
  # Include these modules in the bundle
  included_files = ["prisma/**/*"]
  # Set specific environment variables for functions
  [functions.environment]
    NODE_ENV = "production"
    DEBUG = "*"

# Simple redirects for API endpoints
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Test function redirect for diagnostics
[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200
  force = true

# Database check function redirect
[[redirects]]
  from = "/db-check"
  to = "/.netlify/functions/db-check"
  status = 200
  force = true

# Database initialization function redirect
[[redirects]]
  from = "/db-init"
  to = "/.netlify/functions/db-init"
  status = 200
  force = true

# Prisma migration function redirect
[[redirects]]
  from = "/prisma-migrate"
  to = "/.netlify/functions/prisma-migrate"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables are already defined above
