[build]
  publish = "public"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "public"

# Function configuration
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For better cold start performance
[build.environment]
  NODE_VERSION = "18"
