name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Use GitHub-hosted PostgreSQL instead of Docker service
    # This avoids Docker-related issues in the GitHub Actions environment
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Setup test database for CI
      run: |
        # Temporarily modify the Prisma schema to use SQLite for testing
        echo "Setting up SQLite for CI testing"
        # Backup the original schema
        cp prisma/schema.prisma prisma/schema.prisma.backup
        # Update the schema to use SQLite
        sed -i 's/provider = "postgresql"/provider = "sqlite"/' prisma/schema.prisma
        # Generate Prisma client with the modified schema
        npx prisma generate
        # Create SQLite database
        touch prisma/test.db
    
    # Skip linting for now as we're focusing on tests
    # - name: Run linting
    #   run: npm run lint || echo "No linting configured"
    
    - name: Run backend tests
      env:
        # Use SQLite for testing
        DATABASE_URL: "file:./prisma/test.db"
        NODE_ENV: "test"
      run: npm run test:backend
    
    - name: Run frontend tests
      run: npm run test:frontend
    
    - name: Generate test coverage report
      env:
        # Use SQLite for testing
        DATABASE_URL: "file:./prisma/test.db"
        NODE_ENV: "test"
      run: npm run test:coverage
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.node-version }}
        path: coverage/
  
  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build application
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ github.run_id }}
        path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build for production
      run: |
        # Build the backend
        npm run build
        # Ensure the netlify/functions directory exists
        mkdir -p netlify/functions
        # Ensure Prisma client is generated
        npx prisma generate
    
    # Use a simple Netlify deployment approach
    - name: Install Netlify CLI
      run: npm install -g netlify-cli
      
    - name: Deploy to Netlify
      run: |
        # Deploy to Netlify using the CLI
        netlify deploy --dir=public --prod --auth="$NETLIFY_AUTH_TOKEN" --site="$NETLIFY_SITE_ID"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      # Note: You need to add NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID secrets in your GitHub repository settings
